### ISSUE TITLE
Design new PCB

### ISSUE THREAD

**Issue by mortenfyhn** [mortenfyhn/coffee-scales#30]
Gotta decide what to include and what to skip.

**Comment by sindrehan** [comment]
Let me know if you want a review of/help with the PCB. Are you using KiCad?

**Comment by mortenfyhn** [comment]
That'd be great! @yttersian is helping out with PCB design, maybe we can all collaborate? I don't remember what he suggested using. @Slattsveen has also offered to help with making an enclosure / machining.

Roughly, the plan for the first pcb revision is

* Still use the full arduino nano 328, and just solder its pin headers to the pcb.
* Get rid of the seven segment display breakouts, get the TM1637 + display circuits onto our board
* Add batteries + battery circuit (rechargeable, or disposable if they last long enough)
* Add a tare button
* Either create a drop-in slot for the HX711 breakout, or re-implement that directly on the board
